-- Cargo pricing on shipments: admin enters weight + price_per_kg,
-- total_price is generated by Postgres so it can never drift from the inputs.
alter table public.shipments
  add column if not exists price_per_kg numeric(12,2),
  add column if not exists total_price numeric(14,2)
    generated always as (round(coalesce(weight, 0) * coalesce(price_per_kg, 0), 2)) stored;

comment on column public.shipments.price_per_kg is 'Rate charged per kilogram, in USD.';
comment on column public.shipments.total_price is 'Auto-calculated: weight x price_per_kg (USD).';
